bookingapp/bkgApp/bkgApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls', namespace='booking')),
    path('', include('csvs.urls', namespace='csvs')),
    path('', include('users.urls', namespace='users'))


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookingapp/bkgApp/booking/urls.py
from django.urls import path

from .views import InventoryListView, BookingList, BookingView, index, registerPage, loginPage, logoutUser

app_name = 'booking'

urlpatterns = [
    path('inventory_list/', InventoryListView.as_view(), name='InventoryList'),
    path('booking_list/', BookingList.as_view(), name='BookingList'),
    path('book/', BookingView.as_view(), name='BookingView'),
    path('register/', registerPage, name='register'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('', index, name='home'),
]

bookingapp/bkgApp/csvs/urls.py
from django.urls import path

from .views import UploadBookingFile, UploadInventoryFile

app_name = 'csvs'

# noinspection SpellCheckingInspection,SpellCheckingInspection
urlpatterns = [
    path('iupload/', UploadInventoryFile.as_view(), name='UploadInventoryFile'),
    path('bupload/', UploadBookingFile.as_view(), name='UploadBookingFile'),

]

bookingapp/bkgApp/users/urls.py
from django.urls import path

from .views import profile, about

app_name = 'users'

urlpatterns = [
    path('profile', profile, name='profile'),
    path('about', about, name='about'),
]

bookingapp/bkgApp/templates/availibility_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form action="" method="POST">
{{form.as_p}}
    {% csrf_token %}
    <button type="submit">Book Trip</button>
</form>



{% endblock %}

bookingapp/bkgApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

        <title>Loader</title>


</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'booking:home' %}">Loader - Welcome: {{ user.username }}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'booking:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'users:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'booking:logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'booking:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'booking:register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Information</h3>
            <p class='text-muted'>
                "{{ user.username }}" Logged In.

            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

bookingapp/bkgApp/templates/home.html
{% extends "base.html" %}
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--  {% block title %}<title>Load File WebPage</title>{% endblock %}-->
<!--  <head>-->
<!--	<title>Login</title>-->
<!--	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">-->
<!--	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
<!--	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">-->

<!--	<style>-->
<!--		body,-->
<!--		html {-->
<!--			margin: 50;-->
<!--			padding: 0;-->
<!--			height: 100%;-->
<!--			background: #7abecc !important;-->
<!--		}-->
<!--		.user_card {-->
<!--			width: 1000px;-->
<!--			margin-top: 150px;-->
<!--			margin-bottom: auto;-->
<!--			background: #74cfbf;-->
<!--			position: centre;-->
<!--			display: flex;-->
<!--			justify-content: center;-->
<!--			flex-direction: row;-->
<!--			padding: 10px;-->
<!--			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			border-radius: 5px;-->

<!--		}-->
<!--        .nav-bar-cust {-->
<!--			width: 500px;-->
<!--			margin-top: 50px;-->
<!--			margin-bottom: auto;-->
<!--			background: #74cfbf;-->
<!--			position: center;-->
<!--			display: flex;-->
<!--			justify-content: center;-->
<!--			flex-direction: row;-->
<!--			padding: 10px;-->
<!--			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);-->
<!--			border-radius: 5px;-->
<!--		}-->
<!--		.form_container {-->
<!--			margin-top: 20px;-->
<!--		}-->

<!--		#form-title{-->
<!--			color: #fff;-->
<!--		}-->
<!--		.login_btn {-->
<!--			width: 100%;-->
<!--			background: #33ccff !important;-->
<!--			color: white !important;-->
<!--		}-->
<!--		.login_btn:focus {-->
<!--			box-shadow: none !important;-->
<!--			outline: 0px !important;-->
<!--		}-->
<!--		.login_container {-->
<!--			padding: 0 2rem;-->
<!--		}-->
<!--		.input-group-text {-->
<!--			background: #f7ba5b !important;-->
<!--			color: white !important;-->
<!--			border: 0 !important;-->
<!--			border-radius: 0.25rem 0 0 0.25rem !important;-->
<!--		}-->
<!--		.input_user,-->
<!--		.input_pass:focus {-->
<!--			box-shadow: none !important;-->
<!--			outline: 0px !important;-->
<!--		}-->
<!--		#hello-mes{-->
<!--		font-size: 18px;-->
<!--		color: #fff;-->
<!--		margin-right: 20px;-->
<!--		}-->

<!--	</style>-->

<!--</head>-->
<!--</head>-->
<!--<body>-->
<!--<div class="container h-100">-->
<!--  <div class="d-flex justify-content-center h-100">-->
<!--      <div class="nav-bar-cust">-->

<!--          <span id="hello-mes">Hello, {{request.user}}</span>-->
<!--        <span id="form-title"><a href="{% url 'booking:logout' %}">Logout</a></span>-->
<!--      </div>-->
<!--        <br/>-->
<!--    <div class="user_card">-->

<!--      -->
<!--  </div>-->
<!--    </div>-->
<!--</body>-->
<!--</html>-->



{% block content %}

{% endblock content %}

bookingapp/bkgApp/templates/index.html
{% extends "home.html" %}

{% block content %}
  <h1 id="form-title">File Load Home</h1>
  <p id="form-title">Welcome to FileLoad, a website developed by <em>ZWJ Venter</em>!</p>
  <h2 id="form-title">Dynamic Content</h2>
  <p id="form-title">The database has the following record counts:</p>
  <ul>
    <li id="form-title"><strong id="form-title">Inventory:</strong> {{ num_inventory }}</li>
    <li id="form-title"><strong id="form-title">Inventory available:</strong> {{ num_instances_available }}</li>
  </ul>
  <h2 id="form-title"> Upload files</h2>
    <p id="form-title">Upload member information via a csv file</p>
    <button type="button">
       <a  href="{% url 'csvs:UploadBookingFile' %}">Upload Booking/ Member Data</a>
    </button>
        <br/>
        <br/>
     <p id="form-title">Upload inventory information via a csv file</p>
    <button type="button" >
       <a href="{% url 'csvs:UploadInventoryFile' %}">Upload Inventory Data</a>
    </button>
        <br/>
        <br/>
    <h2 id="form-title"> Make a Booking</h2>
        <p id="form-title">Make a Booking</p>
    <button type="button">
       <a  href="{% url 'booking:BookingView' %}">Make Booking</a>
    </button>
{% endblock %}

bookingapp/bkgApp/templates/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				{% for message in messages %}
				<p>{{message}}</p>
				{% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'booking:register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>

bookingapp/bkgApp/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
    </div>
{% endblock content %}

bookingapp/bkgApp/templates/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                            {{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
                        {{form.errors}}
						Already have an account? <a href="{% url 'booking:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';
		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

bookingapp/bkgApp/templates/uploadbooking.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <form id="booking" method="POST" class="ui form" enctype="multipart/form-data">
      {% csrf_token %}

      {{form}}
        <button id="txt-mes" type="submit" class="ui button primary"> Confirm </button>
    </form>

{% endblock %}

bookingapp/bkgApp/templates/uploadinventory.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

 <form id="inventory" method="POST" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="ui button secondary"> Confirm </button>
    </form>

{% endblock %}